#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=90

start() {
	mkdir /data
	/bin/mount -t ext4 /dev/mtdblock7 /data
	sleep 2
	if [ -d /data/lost+found/ ]; then
	echo "mount ext4 ok on /data" > /dev/ttyS0
	else
	/bin/umount /data
	sleep 1
	echo "mount failed,repare mkfs" > /dev/ttyS0
	/usr/sbin/mkfs.ext4 /dev/mtdblock7
	echo "mkfs complete,repare to mount" > /dev/ttyS0
	/bin/mount -t ext4 /dev/mtdblock7 /data
	fi
}
